import "../config/env.js";
import mongoose from "mongoose";
import Product from "../models/Product.js";

const products = [
  {
    name: "Silver Heart Charm Bracelet",
    slug: "silver-heart-charm-bracelet",
    sku: "HP-BRC-007",
    category: "Bracelets",
    collection: "Most Gifted",
    shortDescription: "Sterling silver bracelet with a delicate heart charm",
    description: "A lightweight bracelet designed for everyday gifting, finished with a polished heart charm and adjustable chain.",
    price: 2199,
    compareAtPrice: 3999,
    stock: 22,
    metal: "Silver",
    metalPurity: "925 Sterling Silver",
    gemstone: "Zircon",
    weightInGrams: 4.8,
    size: "Adjustable",
    color: "Silver",
    craftsmanship: "Polished charm finish",
    careInstructions: "Store in a dry pouch and clean with a soft cloth.",
    tags: ["bracelet", "silver", "heart", "gift"],
    images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Gold Floral Open Ring",
    slug: "gold-floral-open-ring",
    sku: "HP-RNG-008",
    category: "Rings",
    collection: "Everyday Sparkle",
    shortDescription: "Open ring with soft floral accents",
    description: "An adjustable floral ring with a warm gold finish and subtle sparkle for daily styling.",
    price: 1899,
    compareAtPrice: 3299,
    stock: 20,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "Zircon",
    weightInGrams: 3.5,
    size: "Adjustable",
    color: "Yellow Gold",
    craftsmanship: "Open floral setting",
    careInstructions: "Avoid perfume and moisture exposure.",
    tags: ["ring", "gold", "floral", "daily wear"],
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Rose Gold Infinity Pendant",
    slug: "rose-gold-infinity-pendant",
    sku: "HP-PND-009",
    category: "Pendants",
    collection: "Love Edit",
    shortDescription: "Infinity pendant in rose gold finish",
    description: "A graceful infinity pendant for gifting, crafted with a rose gold tone and refined stone detailing.",
    price: 2399,
    compareAtPrice: 4599,
    stock: 17,
    metal: "Rose Gold",
    metalPurity: "925 Sterling Silver",
    gemstone: "Zircon",
    weightInGrams: 3.9,
    size: "Pendant with 18 inch chain",
    color: "Rose Gold",
    craftsmanship: "Infinity motif",
    careInstructions: "Keep away from water and store separately.",
    tags: ["pendant", "rose gold", "infinity", "gift"],
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Classic Silver Hoop Earrings",
    slug: "classic-silver-hoop-earrings",
    sku: "HP-ERG-010",
    category: "Earrings",
    collection: "Office Essentials",
    shortDescription: "Clean silver hoops for everyday styling",
    description: "Minimal hoop earrings made for repeat wear, with a clean silver finish and lightweight profile.",
    price: 1599,
    compareAtPrice: 2799,
    stock: 28,
    metal: "Silver",
    metalPurity: "925 Sterling Silver",
    gemstone: "",
    weightInGrams: 3.1,
    size: "Medium hoops",
    color: "Silver",
    craftsmanship: "Smooth hoop profile",
    careInstructions: "Wipe after use and store in pouch.",
    tags: ["earrings", "hoops", "silver", "everyday"],
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Gold Temple Bangle",
    slug: "gold-temple-bangle",
    sku: "HP-BNG-011",
    category: "Bangles",
    collection: "Festive Edit",
    shortDescription: "Traditional bangle with temple-inspired detail",
    description: "A festive bangle with traditional motif detailing and a polished gold finish for ethnic looks.",
    price: 5499,
    compareAtPrice: 8999,
    stock: 9,
    metal: "Gold",
    metalPurity: "22K Gold Plated",
    gemstone: "Ruby-toned stones",
    weightInGrams: 14.2,
    size: "2.6",
    color: "Antique Gold",
    craftsmanship: "Temple-inspired engraving",
    careInstructions: "Store separately to protect the surface finish.",
    tags: ["bangle", "gold", "temple", "festive"],
    images: ["https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Pearl Layered Necklace",
    slug: "pearl-layered-necklace",
    sku: "HP-NEC-012",
    category: "Necklaces",
    collection: "Wedding Edit",
    shortDescription: "Layered pearl necklace with gold accents",
    description: "An elegant layered necklace featuring pearl detailing and gold accents for wedding and festive styling.",
    price: 6499,
    compareAtPrice: 10999,
    stock: 8,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "Pearl",
    weightInGrams: 18.5,
    size: "Adjustable chain",
    color: "Gold and Pearl White",
    craftsmanship: "Layered pearl setting",
    careInstructions: "Avoid chemical sprays and wipe pearls gently.",
    tags: ["necklace", "pearl", "wedding", "gold"],
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Minimal Gold Chain",
    slug: "minimal-gold-chain",
    sku: "HP-CHN-013",
    category: "Chains",
    collection: "Daily Staples",
    shortDescription: "Simple gold chain for everyday layering",
    description: "A clean everyday chain with a warm gold finish, designed for layering with pendants or wearing solo.",
    price: 2799,
    compareAtPrice: 4999,
    stock: 21,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "",
    weightInGrams: 5.7,
    size: "18 inch",
    color: "Yellow Gold",
    craftsmanship: "Fine link chain",
    careInstructions: "Store flat and avoid tugging.",
    tags: ["chain", "gold", "daily wear", "layering"],
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Silver Evil Eye Anklet",
    slug: "silver-evil-eye-anklet",
    sku: "HP-ANK-014",
    category: "Anklets",
    collection: "Charm Edit",
    shortDescription: "Silver anklet with evil eye charm",
    description: "A playful anklet with an evil eye charm and delicate silver chain for casual styling.",
    price: 1799,
    compareAtPrice: 3199,
    stock: 25,
    metal: "Silver",
    metalPurity: "925 Sterling Silver",
    gemstone: "Blue enamel",
    weightInGrams: 3.6,
    size: "Adjustable",
    color: "Silver and Blue",
    craftsmanship: "Charm link finish",
    careInstructions: "Avoid wearing in water.",
    tags: ["anklet", "silver", "evil eye", "charm"],
    images: ["https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Diamond Look Stud Earrings",
    slug: "diamond-look-stud-earrings",
    sku: "HP-ERG-015",
    category: "Earrings",
    collection: "Essentials",
    shortDescription: "Classic stone studs with diamond-like shine",
    description: "Simple and polished stud earrings for office wear, daily looks, and effortless gifting.",
    price: 1299,
    compareAtPrice: 2499,
    stock: 35,
    metal: "Silver",
    metalPurity: "925 Sterling Silver",
    gemstone: "Zircon",
    weightInGrams: 2.4,
    size: "One size",
    color: "Silver",
    craftsmanship: "Prong-set stone",
    careInstructions: "Clean gently with dry cloth.",
    tags: ["earrings", "studs", "zircon", "daily wear"],
    images: ["https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Rose Gold Stackable Ring Set",
    slug: "rose-gold-stackable-ring-set",
    sku: "HP-RNG-016",
    category: "Rings",
    collection: "Stack Edit",
    shortDescription: "Set of stackable rings in rose gold finish",
    description: "A versatile ring set for stacked styling, with mixed textures and a soft rose gold tone.",
    price: 3299,
    compareAtPrice: 5999,
    stock: 13,
    metal: "Rose Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "Zircon",
    weightInGrams: 6.1,
    size: "Adjustable set",
    color: "Rose Gold",
    craftsmanship: "Mixed band textures",
    careInstructions: "Store each ring separately.",
    tags: ["rings", "stackable", "rose gold", "fashion"],
    images: ["https://images.unsplash.com/photo-1603561596112-db1d7d8c01dd?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Gold Mangalsutra Bracelet",
    slug: "gold-mangalsutra-bracelet",
    sku: "HP-MNG-017",
    category: "Mangalsutra",
    collection: "Modern Tradition",
    shortDescription: "Modern mangalsutra bracelet with black bead detail",
    description: "A contemporary mangalsutra bracelet designed for daily wear, with black bead accents and a polished gold finish.",
    price: 3799,
    compareAtPrice: 6999,
    stock: 11,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "Black beads",
    weightInGrams: 7.4,
    size: "Adjustable",
    color: "Gold and Black",
    craftsmanship: "Beaded bracelet construction",
    careInstructions: "Avoid stretching and store separately.",
    tags: ["mangalsutra", "bracelet", "gold", "traditional"],
    images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Silver Moonstone Pendant",
    slug: "silver-moonstone-pendant",
    sku: "HP-PND-018",
    category: "Pendants",
    collection: "Celestial Edit",
    shortDescription: "Moon-inspired pendant with soft shimmer",
    description: "A celestial pendant with moonstone-inspired shine and a delicate silver chain.",
    price: 2599,
    compareAtPrice: 4699,
    stock: 18,
    metal: "Silver",
    metalPurity: "925 Sterling Silver",
    gemstone: "Moonstone",
    weightInGrams: 4.2,
    size: "18 inch chain",
    color: "Silver",
    craftsmanship: "Smooth cabochon setting",
    careInstructions: "Avoid harsh cleaners and wipe gently.",
    tags: ["pendant", "silver", "moonstone", "celestial"],
    images: ["https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Antique Gold Jhumka Earrings",
    slug: "antique-gold-jhumka-earrings",
    sku: "HP-ERG-019",
    category: "Earrings",
    collection: "Festive Edit",
    shortDescription: "Traditional jhumkas with antique gold finish",
    description: "Festive jhumka earrings with intricate detail and an antique gold finish for sarees and ethnic looks.",
    price: 2899,
    compareAtPrice: 5299,
    stock: 15,
    metal: "Gold",
    metalPurity: "22K Gold Plated",
    gemstone: "Ruby-toned stones",
    weightInGrams: 8.9,
    size: "Medium drop",
    color: "Antique Gold",
    craftsmanship: "Traditional jhumka work",
    careInstructions: "Store in a dry box after use.",
    tags: ["jhumka", "earrings", "festive", "gold"],
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Emerald Teardrop Necklace Set",
    slug: "emerald-teardrop-necklace-set",
    sku: "HP-SET-020",
    category: "Jewellery Sets",
    collection: "Wedding Edit",
    shortDescription: "Necklace and earrings set with emerald-toned drops",
    description: "A coordinated necklace set with emerald-toned teardrop stones and a rich gold finish for special occasions.",
    price: 8999,
    compareAtPrice: 14999,
    stock: 7,
    metal: "Gold",
    metalPurity: "22K Gold Plated",
    gemstone: "Emerald-toned stones",
    weightInGrams: 24.5,
    size: "Adjustable necklace",
    color: "Gold and Emerald",
    craftsmanship: "Coordinated stone setting",
    careInstructions: "Store the set flat and avoid perfume.",
    tags: ["jewellery set", "necklace set", "wedding", "emerald"],
    images: ["https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Platinum Finish Couple Bands",
    slug: "platinum-finish-couple-bands",
    sku: "HP-RNG-021",
    category: "Rings",
    collection: "Couple Edit",
    shortDescription: "Minimal couple bands with platinum finish",
    description: "A pair of polished couple bands with a clean platinum look for anniversaries and commitment gifting.",
    price: 5999,
    compareAtPrice: 9999,
    stock: 10,
    metal: "Platinum",
    metalPurity: "Platinum Finish",
    gemstone: "Zircon",
    weightInGrams: 9.2,
    size: "Custom sizes",
    color: "Platinum",
    craftsmanship: "Smooth comfort-fit bands",
    careInstructions: "Avoid scratches and store separately.",
    tags: ["rings", "couple bands", "platinum", "anniversary"],
    images: ["https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Gold Charm Anklet",
    slug: "gold-charm-anklet",
    sku: "HP-ANK-022",
    category: "Anklets",
    collection: "Vacation Edit",
    shortDescription: "Gold anklet with small hanging charms",
    description: "A playful charm anklet with warm gold finish, designed for casual outfits and festive travel looks.",
    price: 1999,
    compareAtPrice: 3499,
    stock: 19,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "",
    weightInGrams: 4.7,
    size: "Adjustable",
    color: "Yellow Gold",
    craftsmanship: "Charm link chain",
    careInstructions: "Avoid beach water and store dry.",
    tags: ["anklet", "gold", "charm", "vacation"],
    images: ["https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "White Gold Drop Pendant",
    slug: "white-gold-drop-pendant",
    sku: "HP-PND-023",
    category: "Pendants",
    collection: "Minimal Luxury",
    shortDescription: "Drop pendant with white gold finish",
    description: "A sleek drop pendant with a white gold finish and brilliant stone detail for refined everyday styling.",
    price: 3099,
    compareAtPrice: 5699,
    stock: 16,
    metal: "White Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "Zircon",
    weightInGrams: 4.4,
    size: "18 inch chain",
    color: "White Gold",
    craftsmanship: "Drop stone setting",
    careInstructions: "Keep dry and clean with soft cloth.",
    tags: ["pendant", "white gold", "minimal", "zircon"],
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Gold Beaded Bracelet Stack",
    slug: "gold-beaded-bracelet-stack",
    sku: "HP-BRC-024",
    category: "Bracelets",
    collection: "Layering Edit",
    shortDescription: "Set of gold-toned beaded bracelets",
    description: "A stackable bracelet set with beaded texture, designed for layering with watches and bangles.",
    price: 2699,
    compareAtPrice: 4899,
    stock: 20,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "",
    weightInGrams: 8.1,
    size: "Stretch fit",
    color: "Yellow Gold",
    craftsmanship: "Beaded stretch construction",
    careInstructions: "Avoid overstretching and moisture.",
    tags: ["bracelet", "stack", "gold", "layering"],
    images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
  {
    name: "Ruby Halo Cocktail Ring",
    slug: "ruby-halo-cocktail-ring",
    sku: "HP-RNG-025",
    category: "Rings",
    collection: "Party Edit",
    shortDescription: "Cocktail ring with ruby-toned centre stone",
    description: "A statement cocktail ring featuring a ruby-toned centre stone surrounded by sparkling halo detail.",
    price: 3899,
    compareAtPrice: 7299,
    stock: 12,
    metal: "Gold",
    metalPurity: "18K Gold Plated",
    gemstone: "Ruby-toned stone",
    weightInGrams: 5.5,
    size: "13",
    color: "Gold and Ruby",
    craftsmanship: "Halo stone setting",
    careInstructions: "Avoid impact and store in ring box.",
    tags: ["ring", "cocktail", "ruby", "party"],
    images: ["https://images.unsplash.com/photo-1603561596112-db1d7d8c01dd?auto=format&fit=crop&w=900&q=80"],
    isFeatured: true,
    isActive: true,
  },
  {
    name: "Silver Minimal Nose Pin",
    slug: "silver-minimal-nose-pin",
    sku: "HP-NOS-026",
    category: "Nose Pins",
    collection: "Daily Staples",
    shortDescription: "Tiny silver nose pin with clean zircon shine",
    description: "A minimal nose pin designed for daily styling, with a small zircon accent and comfortable silver finish.",
    price: 899,
    compareAtPrice: 1599,
    stock: 40,
    metal: "Silver",
    metalPurity: "925 Sterling Silver",
    gemstone: "Zircon",
    weightInGrams: 0.8,
    size: "Standard",
    color: "Silver",
    craftsmanship: "Tiny prong-set stone",
    careInstructions: "Clean before storing and keep dry.",
    tags: ["nose pin", "silver", "minimal", "daily wear"],
    images: ["https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=900&q=80"],
    isFeatured: false,
    isActive: true,
  },
];

const run = async () => {
  if (!process.env.MONGO_URI) {
    throw new Error("MONGO_URI is missing");
  }

  await mongoose.connect(process.env.MONGO_URI, {
    serverSelectionTimeoutMS: 10000,
  });

  let created = 0;
  let skipped = 0;

  for (const product of products) {
    const result = await Product.updateOne(
      { sku: product.sku },
      { $setOnInsert: product },
      { upsert: true }
    );

    if (result.upsertedCount > 0) {
      created += 1;
    } else {
      skipped += 1;
    }
  }

  const total = await Product.countDocuments();
  console.log(`Created ${created} products. Skipped ${skipped} existing products. Total products: ${total}.`);
  await mongoose.disconnect();
};

run().catch(async (error) => {
  console.error(error.message);
  await mongoose.disconnect();
  process.exit(1);
});
